[package]
name = "primal-sieve"
version = "0.2.6"
authors = ["Huon Wilson <dbau.pp@gmail.com>"]

homepage = "https://github.com/huonw/primal"
repository = "https://github.com/huonw/primal"
documentation = "http://huonw.github.io/primal/primal_sieve/"
license = "MIT/Apache-2.0"
keywords = ["math", "mathematics", "primes", "number-theory"]

description = """
A high performance prime sieve.
"""

[dependencies]
primal-bit = { path = "../primal-bit", version = "0.2.2" }
primal-estimate = { path = "../primal-estimate", version = "0.2" }

hamming = "0.1"

[dev-dependencies]
primal-slowsieve = { path = "../primal-slowsieve", version = "0.2" }
primal = { path = "..", version = "0.2" }

[features]
unstable = []
safe = []
