name: Continuous integration
on:
  push:
    branches:
      - staging
      - trying

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: 1.36.0  # MSRV
          - rust: stable
          - rust: beta
          - rust: nightly
          - rust: nightly
            target: i686-unknown-linux-gnu
          - rust: stable
            target: mips64-unknown-linux-gnuabi64

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Tests
        env:
          TARGET: ${{ matrix.target }}
        run: ./ci/script.sh
